### PR TITLE
support containerd

### PR DESCRIPTION
**Pull request by adamzhoul**
as title

### CODE REVIEW

**Comment by adamzhoul** [comment]
@lfbear PTAL
this version now supports using containerd: exec/logs
docker support is removed because it is not needed


PS: docker cp is not supported now. because it is not in cri.

**Comment by adamzhoul** [comment]
besides: /log /cluster/{cluster}/ns/{namespace}/pod/{podName}/container/{containerName} is removed
using /api/v1/log/cluster/{cluster}  directly

because logs -f using HTTP chunk instead, not WebSocket anymore.

**Comment by adamzhoul** [comment]
docker cp is not supported in another way, using tar command in exec command as  `kubectl cp` does
check "/api/v1/file"

**Comment by lfbear** [comment]
Nice well done, let me try :)

**Pull request merged**
